### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by raulchen** [dyng/ctrlsf.vim#161] opened 2017-02-24 05:04 UTC
(1) it would be nice if the search result page opens with full width. then when you open or preview a file, search result shrinks to half page and preview page shows in the other half
(2) is it possible to use the same window for preview and open?  (I have `let g:ctrlsf_auto_close = 0`)

thanks for this awesome plugin!

**Comment by dyng** [comment] 2017-02-25 03:28
1. Good suggestion, current preview window is not easy for reading when `g:ctrlsf_winsize` is over `50%'.

2. What do you mean '**same window** for preview and open'? Do you want to open file in a new window but not last window which you typed `:CtrlSF`?

**Comment by raulchen** [comment] 2017-02-25 04:59
Hi @dyng, thanks for your quick response.

As for the second question, if I set `let g:ctrlsf_auto_close = 0`, then pressing p (preview) and o (open) will open files in two different windows on the right side (see my screenshot below).

![screen shot 2017-02-24 at 20 49 21](https://cloud.githubusercontent.com/assets/2883335/23328309/0b9b291a-fad3-11e6-9fc5-8e930f8738b8.png)

**Comment by dyng** [comment] 2017-02-26 02:09
Ok, I have got your point, thanks.

I think I should know **why you need to set `g:ctrlsf_auto_close = 0`**. The use case I imagined when I first implemented `g:ctrlsf_auto_close` option and set it `false` is

1. open ctrlsf window in left half
2. open file in right half
3. edit something
4. place cursor back to ctrlsf window, open another file
5. repeat 3 -> 4

but it is not the case because we have *Edit Mode* now.

So I guess what you really need is an **editable** preview window, am I right?

**Comment by raulchen** [comment] 2017-02-26 05:47
I set `g:ctrlsf_auto_close = 0` for a couple of reasons:

1) to avoid losing the search result page by accidentally pressing `enter` or `o`. (`CtrlSFToggle` is a little bit inconvenient,  I barely use it. I'd like to close search result page manually after I don't need it any more)
2) to switch focus to preview window (I've found upper case `P` could do that as well now)
3) the use case you mentioned, especially when you want to modify or look for something beyond the context in search result.

Also, even if I remove `g:ctrlsf_auto_close = 0`, there's still a third window with 0 width on the right side when previewing files.

**Comment by amadeus** [comment] 2018-06-25 20:05
Is there a way to make the split ctrlsf generates just follow the general split rules of vim? I find I can't use `<c-w>=` to re-balance splits when it's open.

I tried setting `let g:ctrlsf_winsize = 'auto'` but that didn't appear to help?

**Comment by dyng** [comment] 2018-06-26 03:43
@amadeus This behavior is by design, ctrlsf window has a fixed window width, which is configurable by `g:ctrlsf_winsize`.

**Comment by balta2ar** [comment] 2018-06-26 07:36
3) I'd like to save space and I've set `let g:ctrlsf_context = '-B 0 -A 0'`. However, it still adds these lines with multiple dots... Is there a way to remove them? 

![](https://i.imgur.com/Jofer9d.png)

**Comment by amadeus** [comment] 2018-06-26 08:19
@dyng typically my flow might be that I like to open up some search results, I may then want to open another split, to check something else while keeping both the search results open and a file from it.

There's also this sorta vim philosophy:

http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/

A fixed split is basically like a project drawer

**Comment by dyng** [comment] 2018-06-26 10:13
@balta2ar 

1. Preview window is designed for that purpose, but since you don't like it I'd like to recommend customizing it by yourself, using `g:CtrlSFAfterMainWindowInit`. Here is an example

```vim
func! CtrlSFAfterMainWindowInit
    nnoremap <silent><buffer> <Enter> :call ctrlsf#JumpTo('open') \| call ctrlsf#win#FocusMainWindow()<CR>
endf
```

Why I can't add an option `g:ctrlsf_preview_window` like your suggestion is that preview window has its own mapping and configs, it requires a dedicated buffer.

2. Interesting idea, and looks useful. I'll think whether it is possible in Vim.

3. Currently it's impossible to remove those dots. Why not switching to compact view?

**Comment by balta2ar** [comment] 2018-06-26 12:43
1. I'm OK with that configuration but it looks like if I put it into my vimrc as is, it executes earlier than the plugin code:
```
Error detected while processing /home/ybochkarev/rc.arch/bz/.vim/init.vim:
line 1640:
E123: Undefined function: CtrlSFAfterMainWindowInit
line 1642:
E193: :endfunction not inside a function
```
What's the best way to apply it after the plugin is loaded?

3. I've tried it, and it's great, but it's horizontal. Sometimes I'd prefer to have vertical compact view as well.

**Comment by dyng** [comment] 2018-06-26 12:58
@balta2ar My fault, I missed the parenthesis. Correct one is

```vim
func! CtrlSFAfterMainWindowInit()
    nnoremap <silent><buffer> <Enter> :call ctrlsf#JumpTo('open') \| call ctrlsf#win#FocusMainWindow()<CR>
endf
```

and you need to set `let g:ctrlsf_auto_close = 0` too.

**Comment by balta2ar** [comment] 2018-06-26 13:18
Thanks! I does exactly what I want, however, there is a couple of rough edges: 1) it seems that it still creates a preview window on the top (in my case). It's blank and small, but it's there 2) It highlights the search result line, similar to the current line hightlighting, and it doesn't go away if I move cursor.

**Comment by dyng** [comment] 2018-06-26 13:30
Sorry that I didn't make myself clear enough.  The above command only works for **opening file** with `Enter` key, but not for preview. And the command only maps `Enter` key, you'll need to add another line for mapping `o` key.

```vim
    silent! nnoremap <silent><buffer> o :call ctrlsf#JumpTo('open') \| call ctrlsf#win#FocusMainWindow()<CR>
```

**Comment by balta2ar** [comment] 2018-06-26 14:47
Thank you so much for your help! It's so much better now!

**Comment by balta2ar** [comment] 2018-06-26 15:45
4) In the sidebar filenames are displayed as relative but in compact view they have absolute paths. My root directory is already pretty deep down the dir tree, so the filename sometimes takes the most part of the search results. Is it possible to make filenames relative in compact view?

**Comment by dyng** [comment] 2018-06-27 12:18
@balta2ar I'm sorry that I found it's a bug. Fixed in #223 .

**Comment by balta2ar** [comment] 2018-06-27 12:45
Thank you!

5. Without arguments `:CtrlSF` searches for the word in the cursor. I think what could also be very useful is that if user could search for something by visually selecting it and calling `:CtrlSF` without arguments from Visual mode. What do you think?

**Comment by dyng** [comment] 2018-06-27 13:54
@balta2ar I'm not sure is there any difference from `<Plug>CtrlSFVwordPath`?

**Comment by balta2ar** [comment] 2018-06-27 14:43
Oops, sorry, I missed that...

**Comment by dyng** [comment] 2018-06-29 12:23
The original problem of OP will not be resolved in the short future. Close this issue since it has been off-topic.

**Closed by dyng** 2018-06-29 12:23 UTC
